services:
  pgdb: 
    image: postgres:17-bookworm
    restart: always 
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_DB=root_db
      - POSTGRES_PASSWORD=test
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker-initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    container_name: apiserver
    restart: always
    build: . 
    ports: 
      - 8848:8848
    volumes:
      - .:/go/src/server
    environment:
      - DB_CONNECTION_URI=postgres://dev:pass@pgdb:5432/root_db?sslmode=disable
    depends_on:
      pgdb: 
        condition: service_healthy
  
volumes:
  pg_data: 